/* eslint-disable @typescript-eslint/no-explicit-any */
// THIS FILE IS GENERATED BY GRAPHQL-CODEGEN (see codegen.yml) -- DO NOT EDIT!
import {
  FieldPolicy,
  FieldReadFunction,
  TypePolicies,
  TypePolicy,
} from "@apollo/client/cache";
export type MutationKeySpecifier = ("toggleTask" | MutationKeySpecifier)[];
export type MutationFieldPolicy = {
  toggleTask?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type QueryKeySpecifier = ("tasks" | QueryKeySpecifier)[];
export type QueryFieldPolicy = {
  tasks?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type TaskKeySpecifier = (
  | "completedAt"
  | "dependencyIds"
  | "group"
  | "id"
  | "task"
  | TaskKeySpecifier
)[];
export type TaskFieldPolicy = {
  completedAt?: FieldPolicy<any> | FieldReadFunction<any>;
  dependencyIds?: FieldPolicy<any> | FieldReadFunction<any>;
  group?: FieldPolicy<any> | FieldReadFunction<any>;
  id?: FieldPolicy<any> | FieldReadFunction<any>;
  task?: FieldPolicy<any> | FieldReadFunction<any>;
};
export type StrictTypedTypePolicies = {
  Mutation?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | MutationKeySpecifier
      | (() => undefined | MutationKeySpecifier);
    fields?: MutationFieldPolicy;
  };
  Query?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?:
      | false
      | QueryKeySpecifier
      | (() => undefined | QueryKeySpecifier);
    fields?: QueryFieldPolicy;
  };
  Task?: Omit<TypePolicy, "fields" | "keyFields"> & {
    keyFields?: false | TaskKeySpecifier | (() => undefined | TaskKeySpecifier);
    fields?: TaskFieldPolicy;
  };
};
export type TypedTypePolicies = StrictTypedTypePolicies & TypePolicies;
