// THIS FILE IS GENERATED BY GRAPHQL-CODEGEN (see codegen.yml) -- DO NOT EDIT!
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = {
  [K in keyof T]: T[K];
};
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & {
  [SubKey in K]?: Maybe<T[SubKey]>;
};
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & {
  [SubKey in K]: Maybe<T[SubKey]>;
};
export type MakeEmpty<
  T extends { [key: string]: unknown },
  K extends keyof T,
> = { [_ in K]?: never };
export type Incremental<T> =
  | T
  | {
      [P in keyof T]?: P extends " $fragmentName" | "__typename" ? T[P] : never;
    };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string };
  String: { input: string; output: string };
  Boolean: { input: boolean; output: boolean };
  Int: { input: number; output: number };
  Float: { input: number; output: number };
};

export type Mutation = {
  __typename?: "Mutation";
  toggleTask: Scalars["Boolean"]["output"];
};

export type MutationToggleTaskArgs = {
  toggleTaskInput: ToggleTaskInput;
};

export type Query = {
  __typename?: "Query";
  tasks: Array<Task>;
};

export type Task = {
  __typename?: "Task";
  completedAt?: Maybe<Scalars["String"]["output"]>;
  dependencyIds: Array<Maybe<Scalars["Int"]["output"]>>;
  group: Scalars["String"]["output"];
  id: Scalars["Int"]["output"];
  task: Scalars["String"]["output"];
};

export type ToggleTaskInput = {
  completedAt?: InputMaybe<Scalars["String"]["input"]>;
  taskId: Scalars["Int"]["input"];
};

export type GetTasksQueryVariables = Exact<{ [key: string]: never }>;

export type GetTasksQuery = {
  __typename?: "Query";
  tasks: Array<{ __typename?: "Task"; id: number }>;
};

export const namedOperations = {
  Query: {
    getTasks: "getTasks",
  },
};
