// THIS FILE IS GENERATED BY GRAPHQL-CODEGEN (see codegen.yml) -- DO NOT EDIT!
/* eslint-disable */
import { z } from "zod";
import { ToggleTaskInput } from "./operation-types";

type Properties<T> = Required<{
  [K in keyof T]: z.ZodType<T[K], any, T[K]>;
}>;

type definedNonNullAny = {};

export const isDefinedNonNullAny = (v: any): v is definedNonNullAny =>
  v !== undefined && v !== null;

export const definedNonNullAnySchema = z
  .any()
  .refine((v) => isDefinedNonNullAny(v));

export function ToggleTaskInputSchema(): z.ZodObject<
  Properties<ToggleTaskInput>
> {
  return z.object({
    completedAt: z.string().nullish(),
    taskId: z.number(),
  });
}
